 ## Numpy and Pandas Libraries

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

#### Numpy Arrays

In [ ]:
#one dimensional array

arr1 = np.array([1,2,3,4,5])
print(f"one dimensional array: {arr1}")

one dimensional array: [1 2 3 4 5]


In [ ]:
#two dimensional array (matrix)

arr2 = np.array([[1,2,3],[4,5,6]])
print(f"two dimensional array: \n{arr2}")

two dimensional array: 
[[1 2 3]
 [4 5 6]]


In [ ]:
#three dimensional array

arr3 = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])
print(f"three dimensional array: \n{arr3}")

three dimensional array: 
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [ ]:
arr = np.array([[10,20,30],[40,50,60]])

print(f"Array: \n {arr}")

print(f"Dimension Count (ndim): \n {arr.ndim}")
print(f"Shape : \n {arr.shape}")
print(f"Item Count (size) : \n {arr.size}")
print(f"Data type (dtype): \n{arr.dtype}")
print(f"Byte size in memory : \n {arr.itemsize}")




Array: 
 [[10 20 30]
 [40 50 60]]
Dimension Count (ndim): 
 2
Shape : 
 (2, 3)
Item Count (size) : 
 6
Data type (dtype): 
int64
Byte size in memory : 
 8


### Python list <-> Numpy array

In [ ]:
py_list = [1,2,3,4,5 ]

arr = np.array(py_list)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
back_to_list = arr.tolist()
print(back_to_list)
print(type(back_to_list))

[1, 2, 3, 4, 5]
<class 'list'>


Data Types (dtype)

In [ ]:
arr1 = np.array([1,2,3], dtype= np.float32)
print(f"Float arr: {arr1}")

Float arr: [1. 2. 3.]


In [ ]:
arr2 = np.array([1.1,2.2,3.3], dtype=np.int32)
print(arr2)

[1 2 3]


### Creating Array Functions

In [ ]:
print(f"array created from zeros: \n {np.zeros((2,3))}")

array created from zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(f"array created from ones: \n {np.ones((3,5))}")

array created from ones: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
print(f"array defined by range (Increase from 0 to 10 in increments of 2.): \n {np.arange(0,10,2)}")
#the first item included, the last item not included

array defined by range (Increase from 0 to 10 in increments of 2.): 
 [0 2 4 6 8]


In [ ]:
print(f"array with equal intervals: \n {np.linspace(0,10,5)}")
#5 numbers from 0-10

array with equal intervals: 
 [ 0.   2.5  5.   7.5 10. ]


### Array Creating Functions

In [ ]:
import numpy as np

#zeros,ones,full

print(f"zeros: \n {np.zeros((2,3))}")
print(f"ones: \n {np.ones((3,5))}")
print(f"full: \n {np.full((2,4),7)}")

zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]]
ones: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full: 
 [[7 7 7 7]
 [7 7 7 7]]


In [ ]:
#arrange, linspace, logspace

print(f"arange: \n {np.arange(10)}")
print(f"linspace: \n{np.linspace(0,1,5)}")
print( f"logspace: \n{np.logspace(0,3,4)}") #10^0 ile 10^3 arasında logaritmik aralık 4 adet sayı oluştur.



arange: 
 [0 1 2 3 4 5 6 7 8 9]
linspace: 
[0.   0.25 0.5  0.75 1.  ]
logspace: 
[   1.   10.  100. 1000.]


In [ ]:
# eye and identity

print(f"Create a 3x3 identity matrix. \n {np.eye(3)}")
print(f"Create a 4x4 identity matrix. \n {np.identity(4)}")

Create a 3x3 identity matrix. 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Create a 4x4 identity matrix. 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# empty and empty_like

print(f"empty: \n {np.empty((2,3), dtype=np.float32)}")

arr = np.array([[1,2,3],[4,5,6]])
empty_like_arr = np.empty_like(arr)
print(f"empty_like_arr: \n {empty_like_arr}")

empty: 
 [[0.    1.875 0.   ]
 [1.875 0.    1.875]]
empty_like_arr: 
 [[0 0 0]
 [0 0 0]]


In [ ]:
# tile ve repeat
print(f"tile: \n {np.tile([1,2,3], 3)}")
print(f"repeat: \n {np.repeat([1,2,3],2)}")

tile: 
 [1 2 3 1 2 3 1 2 3]
repeat: 
 [1 1 2 2 3 3]


## Indexing and Slicing

### Basic Indexing


In [ ]:
#one dimensional array

arr1 = np.array([10,20,30,40,50])
arr1



array([10, 20, 30, 40, 50])

In [ ]:
print(f"First item: {arr1[0]}")

First item: 10


In [ ]:
print(f"Last item: {arr1[4]}")
print(f"Last item: {arr1[-1]}")

Last item: 50
Last item: 50


In [ ]:
print(f"First 3 items: {arr1[0:3]}")

First 3 items: [10 20 30]


In [ ]:
print(f"Last 2 items: {arr1[-2:]}")

Last 2 items: [40 50]


In [ ]:
#two dimensional array

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(f"Item in row 2, column 3: \n{arr2[1,2]}")

Item in row 2, column 3: 
6


In [ ]:
print(f"First line : \n{arr2[0, :]}")

First line : 
[1 2 3]


In [ ]:
print(f"Second column: \n{arr2[: , 1]}")

Second column: 
[2 5 8]


### Fancy Indexing (Selection by list or array)

In [ ]:
arr = np.array([10,20,30,40,50])

#when we want to select specific indexes
fancy = arr[[0,2,4]]
print(f"Fancy index: {fancy}")

Fancy index: [10 30 50]


In [ ]:
#two dimensional example

arr2 = np.array([[10,20],[30,40],[50,60]])
arr2

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
rows = [0,2]
cols = [0,1]
print(f"Selected items: {arr2[rows,cols]}")

Selected items: [10 60]


### Boolean Indexing

In [ ]:
arr = np.array([5,10,15,20,25])

bool_index = arr[arr > 15]
print(f"Items greater than 15: {bool_index}")

Items greater than 15: [20 25]


In [ ]:
print(f"Select even numbers: {arr[arr % 2 == 0]}")

Select even numbers: [10 20]


### changing array with assignment


In [ ]:
arr = np.array([1,2,3,4,5])
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [ ]:
arr[2:4] = [77,88]
arr

array([99,  2, 77, 88,  5])

### View vs Copy

In [ ]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
slice_view = arr[1:4]
slice_view[:] = 0
print(arr)

[10  0  0  0 50]


In [ ]:
arr2 = np.array([10,20,30,40,50])
arr2

array([10, 20, 30, 40, 50])

In [ ]:
slice_copy = arr2[1:4].copy()
slice_view[:] = 0
print(arr2)
slice_copy

[10 20 30 40 50]


array([20, 30, 40])

## Array Operations

### Scaler Operations

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
print(f"Multiply every item by 2 : {arr * 2}")
print(f"Plus 5 to every item: {arr + 5}")
print(f"Minus 10 from every item: {arr -10}")
print(f"Divide every item by 5: {arr /5}")

Multiply every item by 2 : [ 20  40  60  80 100]
Plus 5 to every item: [15 25 35 45 55]
Minus 10 from every item: [ 0 10 20 30 40]
Divide every item by 5: [ 2.  4.  6.  8. 10.]


### Item Operations

In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

print(f"Addition: {arr1 + arr2}")
print(f"Addition: {np.add(arr1,arr2)}")
print(f"Subtraction: {arr1 - arr2}")
print(f"Subtraction: {np.subtract(arr1,arr2)}")
print(f"Multiplication: {arr1 * arr2}")
print(f"Multiplication: {np.multiply(arr1,arr2)}")
print(f"Division: {arr1 / arr2}")
print(f"Division: {np.divide(arr1,arr2)}")


Addition: [11 22 33 44]
Addition: [11 22 33 44]
Subtraction: [ -9 -18 -27 -36]
Subtraction: [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Multiplication: [ 10  40  90 160]
Division: [0.1 0.1 0.1 0.1]
Division: [0.1 0.1 0.1 0.1]


### Universal Functions (ufuncs)

* sqrt, exp, log, sin, cos, tan ...

In [ ]:
arr = np.array([1,4,9,16,25])
arr

array([ 1,  4,  9, 16, 25])

In [ ]:
print(f"Square root: {np.sqrt(arr)}")
print(f"Exponentiation (e^x): \n {np.exp(arr)}")
print(f"logarithm: \n {np.log(arr)}")
print(f"sin: \n {np.sin(arr)}")
print(f"cos: \n {np.cos(arr)}")

Square root: [1. 2. 3. 4. 5.]
Exponentiation (e^x): 
 [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
logarithm: 
 [0.         1.38629436 2.19722458 2.77258872 3.21887582]
sin: 
 [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
cos: 
 [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]


### Statistical Functions

* sum, mean, median, var, min, max, std

In [ ]:
arr = np.array([5,10,15,20,25])
print(f"sum: {np.sum(arr)}")
print(f"mean: {np.mean(arr)}")
print(f"median: {np.median(arr)}")
print(f"variance: {np.var(arr)}")
print(f"standard deviation: {np.std(arr)}")
print(f"minimum: {np.min(arr)}")
print(f"maximum: {np.max(arr)}")
print(f"minimum index: {np.argmin(arr)}")
print(f"maximum index: {np.argmax(arr)}")


sum: 75
mean: 15.0
median: 15.0
variance: 50.0
standard deviation: 7.0710678118654755
minimum: 5
maximum: 25
minimum index: 0
maximum index: 4


### Cumulative Operations

In [ ]:
arr = np.array([1,2,3,4,5])
print(f"cumsum: {np.cumsum(arr)}")
print(f"cumprod: {np.cumprod(arr)}")


cumsum: [ 1  3  6 10 15]
cumprod: [  1   2   6  24 120]


## Shape Operations

### Reshaping an array

In [ ]:
import numpy as np

arr = np.arange(12)
print(arr)
len(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


12

In [ ]:
reshaped = arr.reshape(3,4) #3x4 matrix
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Converting to 1D

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(f"ravel: {arr.ravel()}") #view

ravel: [1 2 3 4 5 6]


In [ ]:
print(f"Flatten: {arr.flatten()}") #copy

Flatten: [1 2 3 4 5 6]


### Transpose

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(f"Transpose: \n {arr.T}")

Transpose: 
 [[1 4]
 [2 5]
 [3 6]]


### Adding / Removing Dimension

In [ ]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
arr.shape

(3,)

In [ ]:
expanded = np.expand_dims(arr, axis=0) #add row
expanded.shape

(1, 3)

In [ ]:
squuezed = np.squeeze(expanded) #remove row
squuezed.shape

(3,)

### Concatenation

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]]


In [ ]:
#General merge
concat = np.concat((a,b), axis=0)
concat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Vertical merge
vstacked = np.vstack((a,b))
vstacked

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Horizontal merge
hstacked = np.hstack((a,np.array([[7],[8]])))
hstacked

array([[1, 2, 7],
       [3, 4, 8]])

### Splitting Array

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(f"split: {np.split(arr,5)}") #Splits it into 5 equal parts.

split: [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [ ]:
print(f"split: {np.array_split(arr,4)}") # Splits it into 4 parts

split: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]
